Fix how the dig command is used in our code
- Finish foreman setup
- Update .env example file with REDIS_URL
- Add .ruby-gemset file

The main changes in this commit are intended to resolve the following errors that appeared when testing the process of creating a new workflow:

Started POST "/webhooks/donation_given" for 107.178.232.240 at 2020-12-06 23:41:08 +0000
Processing by WebhooksController#donation_given as JSON
  Parameters: {"webhook"=>{}}
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms | Allocations: 825)
NoMethodError (undefined method `[]' for nil:NilClass):
app/controllers/webhooks_controller.rb:14:in `process_donation!'
app/controllers/webhooks_controller.rb:5:in `donation_given'
heroku[router]: at=info method=POST path="/webhooks/donation_given" host=raisenation.herokuapp.com request_id=964ffedb-5a25-4633-98ab-7054a60fb3cb fwd="107.178.232.240" dyno=web.1 connect=0ms service=7ms status=500 bytes=243 protocol=https

Started POST "/workflows" for 180.150.39.119 at 2020-12-06 23:41:03 +0000
Processing by WorkflowsController#create as HTML
  Parameters: {"authenticity_token"=>"+LzIjhr/gY4HV7pNBsahaNtD1vtqESW2u2sh3sxfSDFNz09G8UN6rPi5XQb0wCVRPAVUTi0pjdu0C+r6+0vw3g==", "workflow"=>{"name"=>"Raisely to NationBuilder Test", "source_type"=>"RaiselyCampaign", "target_type"=>"Nation", "source_id"=>"2", "target_id"=>"5", "donor_tags"=>["", "Donor"], "recurring_donor_tags"=>["", "Recurring donor"], "donation_tracking_slug"=>"one-off donation", "recurring_donation_tracking_slug"=>"recurring donation"}, "commit"=>"Save"}
Completed 500 Internal Server Error in 5054ms (ActiveRecord: 11.0ms | Allocations: 9623)
NoMethodError (undefined method `dig' for nil:NilClass):
app/models/raisely_campaign.rb:38:in `create_webhook'
app/models/workflow.rb:54:in `process_webhook!'